# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 923d8205f8071bcd7eb0e8eaca4b37bb0bc9f3ff881a8c9dfc9f59ca4de802ee9c06ac5ba11b60ff8e9f2f670783e8beea14e71e52a38567922ca16bad117d27

test:
  secret_key_base: 56a04cf39615198fcd14c4516e99f82a5692207b8897baeebb6da094774883c30254c70696cfce662be6090be75ebdb118df70184066dd5b6e44e5e4edaa06fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
